### ISSUE TITLE
多语言支持

### ISSUE THREAD

**Issue by postyizhan** [8aka-Team/Invero#2]
```
Kether:
  auto-placeholder-translate: true

Workspaces:
  filter: '^(?![#!]).*\.(?i)(conf|hocon|yaml|yml|toml|json)$'
  paths:
    - 'plugins/Invero/workspace'

Database:
  # Local: SQLITE
  # External: SQL, MONGODB
  type: SQLITE
  sql:
    host: localhost
    port: 3306
    user: root
    password: root
    database: test
    table: invero_data

Patch:
  # 允许在 Vanilla Inventory 中使用 Raw Title
  # 详见 https://github.com/TabooLib/taboolib/blob/dev/6.2.3/module/bukkit/bukkit-ui/src/main/kotlin/taboolib/module/ui/MenuBuilder.kt#L40
  enable-raw-title-in-vanilla-inventory: false
```

虽然有 lang 文件夹，但是看起来没有地方配置语言，以及源码中只有 zh_CN
