### ISSUE TITLE
自定头颅问题

### ISSUE THREAD

**Issue by ItsDApples** [8aka-Team/Invero#4]
![Image](https://github.com/user-attachments/assets/ef939f56-1a91-4e34-82d7-afcd5fe87b48)

```
title: "Test"
layout: |-
  #########
  |       |
  |A B C D|
  |       |
  #########

icons:
  '#':
    material: blue stained glass pane
    name: ' '
  '|':
    material: light blue stained glass pane
    name: ' '
  'A':
    head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTRmNWZhNDc0YTE4ZWEyMWIyYjZiOTMxZTViMjY0ZTIyZGZiYTJjY2NiNjE2NGM1NjczMGJhZjFkZGI5NTFkMSJ9fX0=
    name: '1'
    lore: ""
    action:
      left:
      - menu close
      - 'command "ins" as player'
  'B':
    head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTQ2Yzc1ZjJkZTIwY2UxOWQ5NWI4NzNmOTE4MjYzZjkyOGJiOTlkODgzNmFlZWU4ZDljMjk0Yjc0YTI0YTA3MSJ9fX0=
    name: '2'
    lore: ""
    action:
      left:
      - menu close
      - 'command "ins" as player'
```
